<?php

/**
 * Api
 */
namespace api\modules\v1\controllers;

use api\controllers\BaseController;

class GoodsController extends BaseController
{
    public $modelClass = 'common\models\User';

    public function actionIndex(){
        return 123;
    }
    public function actions()
    {
        $action= parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index']);
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
    }
}